stages:
  - test

test_tun_job:
  stage: test
  tags:
    - gb-ruuner
  only:
    - lesson_8
  script:
    - mvn clean test -DsuiteXmlFile=testNG.xml
  artifacts:
    when: always
    paths:
      - allure-results
