default:
  tags:
    - gb-runner

before_script:
  - echo "перед каждой job"

stages:
  - fail
  - secret
  - precondition
  - test

test_tun_job:
  stage: test
  only:
    - lesson_8
  script:
    - mvn clean test -DsuiteXmlFile="testNG.xml"
  artifacts:
    when: always
    paths:
      - allure-results

get_secret_job:
  stage: secret
  only:
    - lesson_8_ignore
  script:
    - echo $MY_SECRET

python_job:
  stage: precondition
  only:
    - lesson_8_ignore
  script:
    - python3 "test.py" $MY_SECRET
  when: manual

fail_job:
  stage: fail
  only:
    - lesson_8_ignore
  script:
    - python3 "fail.py"
  allow_failure: true
