stages:
  - fail
  - secret
  - precondition
  - test

test_tun_job:
  stage: test
  tags:
    - gb-runner
  only:
    - lesson_8
  script:
    - mvn clean test -DsuiteXmlFile="testNG.xml"
  artifacts:
    when: always
    paths:
      - allure-results

get_secret_job:
  stage: secret
  tags:
    - gb-runner
  only:
    - lesson_8_ignore
  script:
    - echo $MY_SECRET

python_job:
  stage: precondition
  tags:
    - gb-runner
  only:
    - lesson_8_ignore
  script:
    - python test.py $MY_SECRET
  when: manual

fail_job:
  stage: fail
  tags:
    - gb-runner
  only:
    - lesson_8_ignore
  script:
    - python fail.py
  allow_failure: true
