stages:
  - precondition
  - test

test_tun_job:
  stage: test
  tags:
    - gb-runner
  only:
    - lesson_8
  script:
    - mvn clean test -DsuiteXmlFile="testNG.xml"
  artifacts:
    when: always
    paths:
      - allure-results

python_job:
  stage: precondition
  tags:
    - gb-runner
  only:
    - lesson_8_ignore
  script:
    - python test.py
